Dev/andy/designfix - Some design fixing & little improvments
For-Hives/admin-formenu pull request #92
Opened 2023-11-21 23:57 UTC by CinquinAndy

Improve toggle components, 
Menu page
Menu with dish & ingredient page
Nav bar
background
colors
Theming by nextui
Button & input by nextui
Toggler by nextui
add react toastify
handle login failure
some fixs (icons // design system)

2023-11-22 07:26 UTC, WadeFade commented on src/stores/menu.json
a supprimer ?

2023-11-22 08:21 UTC, LightInn requested changes
:heart:

2023-11-22 08:21 UTC, LightInn commented on src/app/auth/signin/page.js
> +							width={1300}
ca fait pas de la merde de forcer les valeur ici ?

2023-11-22 08:21 UTC, LightInn commented on src/app/cartes/page.js
> +			<main className="flex min-h-screen w-full flex-col gap-6 overflow-hidden py-8 pl-[calc(250px+4rem)] pr-16">
mettre un commentaire pour pas se poser la question du calc a chaque fois qu'on passe dessus 

```suggestion
			{/* 250px + 4rem -> espace pour ne pas passer sous la navbar     */}
			<main className="flex min-h-screen w-full flex-col gap-6 overflow-hidden py-8 pl-[calc(250px+4rem)] pr-16">
```

2023-11-22 08:21 UTC, LightInn commented on src/stores/menu.json
a la rigueur faire un dossier `mock` avec les mock des retours d'api dedans si tu veux utiliser quelquechoses style wiremock

2023-11-22 08:21 UTC, LightInn commented on src/components/Nav/Nav.component.js
> +		disabled: false,
On peux penser positivement ? genre `enable : true`

2023-11-22 08:21 UTC, LightInn commented on src/components/Toggle/ToggleDish.component.js
> +	const res = await fetch(
proposition : Avoir la logique dans des fichiers de services (on a deja le `getMenu` pour les call, on pourrais avoir un `dish.service.js` pour gerer les plats etc ? )


Vous en pensé quoi @CinquinAndy @WadeFade

2023-11-22 08:21 UTC, LightInn commented on src/components/Toggle/ToggleIngredient.component.js
> +		throw new Error('Failed to PUT data')
faudrais utiliser le toastify pour handle tout les erreurs des retours logique comme ca

2023-11-22 08:21 UTC, LightInn commented on src/components/Toggle/ToggleMenu.component.js
> +		// This will activate the closest `error.js` Error Boundary
On a des errors boundary ?

2023-11-22 08:21 UTC, LightInn commented on src/app/error.js
> +export default function Error() {
ah oui my bad, on a un error boundary !

2023-11-22 08:21 UTC, LightInn commented on src/app/error.js
> +export default function Error() {
mais c'est peux etre un peux violent de mettre une full page d'erreur en cas de retour d'erreur ? on pourrais essayer d'utiliser les toast au maximum nan ?

2023-11-22 09:25 UTC, CinquinAndy commented on src/stores/menu.json
c'était juste sur la partie débugage, je delete

2023-11-22 09:29 UTC, CinquinAndy commented on src/app/api/auth/[...nextauth]/route.js
> -		error: '/auth/error',
si si , c'est juste que ça fonctionne plus de la même manière à cause de next 14 
Les fichiers "error.js" sont traiter en dehors du scope du routeur de next et n'est pas un fichier lambda (convention de nommage etc)

2023-11-22 09:35 UTC, CinquinAndy commented on src/app/api/auth/[...nextauth]/route.js
> -		error: '/auth/error',
du coup y'a quand même du traitement d'erreur mais directement dans la fonction de login, on fait sans page spécifique d'erreur

2023-11-22 09:37 UTC, CinquinAndy commented on src/app/auth/signin/page.js
> +												<Input
Là j'utilise le "Input" de NextUI pour le coup, les couleurs et thèmes sont dans les fichiers de conf de tailwind.config.js
Ceci dit, ça pourrait être une idée de généraliser des éléments, (après pour le moment c'est pas trop trop le cas), y'a pas grand chose de partager entre les deux app' mise à part le thème général de colorimétrie

2023-11-22 09:54 UTC, CinquinAndy commented on src/app/auth/signin/page.js
> +							width={1300}
nop', c'est même très bien : 
https://nextjs.org/docs/pages/api-reference/components/image

2023-11-22 09:54 UTC, CinquinAndy commented on src/app/auth/signin/page.js
> +							width={1300}
Après on pourrait très bien réduire la taille, mais ça réduit pas mal la qualité vu que l'image doit prendre la taille complète du bloc

2023-11-22 09:55 UTC, CinquinAndy commented on src/app/auth/signin/page.js
> +							width={1300}
on pourrait peut être la mettre en absolute & en fill ceci dit

2023-11-22 10:44 UTC, CinquinAndy commented on src/app/cartes/page.js
> +			<main className="flex min-h-screen w-full flex-col gap-6 overflow-hidden py-8 pl-[calc(250px+4rem)] pr-16">
done, bonne idée

2023-11-22 10:48 UTC, CinquinAndy commented on src/components/Nav/Nav.component.js
> +		disabled: false,
vriament inutile celui là de commentaire, mais ça me fait rire de le prendre en compte

2023-11-22 10:48 UTC, CinquinAndy commented on src/components/Toggle/ToggleDish.component.js
> +	const res = await fetch(
yes bonne idée ça

2023-11-22 11:11 UTC, CinquinAndy commented on src/components/Toggle/ToggleIngredient.component.js
> +		throw new Error('Failed to PUT data')
done, sur les switchs etc :d

2023-11-22 11:11 UTC, CinquinAndy commented on src/components/Toggle/ToggleMenu.component.js
> +		// This will activate the closest `error.js` Error Boundary
https://nextjs.org/docs/app/building-your-application/routing/error-handling

2023-11-22 11:12 UTC, CinquinAndy commented on src/app/error.js
> +export default function Error() {
sur les erreurs de routing ça tombe sur le boundary

2023-11-22 12:02 UTC, WadeFade commented on src/app/auth/signin/page.js
> +												<Input
Oui c'est une bonne idée si on se rend compte que pas mal de composants récurrents sont présent dans les différentes app

2023-11-22 12:02 UTC, LightInn commented on src/app/error.js
> +export default function Error() {
Mais la cetais pas des erreur de routing, la cetais des erreur de service

2023-11-22 12:04 UTC, WadeFade commented on src/components/Toggle/ToggleDish.component.js
> +	const res = await fetch(
ça reste le fonctionnement du composant, est-ce qu'on veut split un composant en plusieurs fichiers ? je sais pas ce qui est le mieux mais ça peut être chiant d'avoir 3 fichiers pour un seul petit composant

2023-11-22 12:07 UTC, LightInn commented on src/app/auth/signin/page.js
> +												<Input
bon du coup c'est marquer dans l'issue #93 je close

2023-11-22 12:08 UTC, LightInn commented on src/components/Toggle/ToggleDish.component.js
> +	const res = await fetch(
C'est dans le but de separer le coté visuler / interactif du "composant" de sa logique des call qui devrais independante de ce a quoi ressemble le bouton ou de comment il change de couleurs

2023-11-23 08:14 UTC, LightInn approved these changes

2023-11-23 08:24 UTC, merged